---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

#use command module
  - name: download filebeat deb
    command: curl -L -O curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

#use command module
  - name: install filebeat deb
    command: sudo dpkg -i filebeat-7.6.1-amd64.deb
#use copy module
  - name: copy over and drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: start filebeat service
    command: service filebeat start
